// Original pixel art for fun mode. One character per pixel, '.' is transparent.
// Palette entries are a fill color, or { fill, cls } to put that color in its own class (for animation).

// Black mage tribute (Vivi, Final Fantasy IX). Drawn from scratch for this site, not a ripped sprite.
export const vivi = {
  rows: [
    '.........hhh',
    '........hHHHh',
    '.........hhHHh',
    '...........hHHh',
    '..........hHHHh',
    '.........hHHHHh',
    '........hHHHHHHh',
    '........hHHHHHHh',
    '.......hHHHHHHHHh.....oo',
    '.......ddddddddddd....oo',
    '...hhhHHHHHHHHHHHHHhh..w',
    '..hHHHHHHHHHHHHHHHHHHh.w',
    '...hhhhKKKKKKKKKKhhhh..w',
    '.......KKKKKKKKKKK.....w',
    '.......KKYYKKKYYKK.....w',
    '.......KKYYKKKYYKK.....w',
    '.......KKKKKKKKKKK.....w',
    '........KKKKKKKKK......w',
    '......cBBBCCCCCBBBc....w',
    '.....bBBBBBCCCBBBBBb...w',
    '....WbBBBBBBBBBBBBBbWWWw',
    '....WWbBBBBBBBBBBBbWWWWw',
    '......bBBBBBBBBBBBb....w',
    '......bBBBBBBBBBBBBb...w',
    '.....bbbbbbbbbbbbbbbb..w',
    '.......PPPP...PPPP.....w',
    '.......PpPP...PPpP.....w',
    '.......PPPP...PPPP.....w',
    '......OOOOO...OOOOO....w',
    '......OOOOO...OOOOO....w',
  ],
  palette: {
    H: '#b8945a',
    h: '#7d5d33',
    d: '#5c4224',
    K: '#120c18',
    Y: { fill: '#ffd23a', cls: 'sprite-eyes' },
    B: '#3b5fb0',
    b: '#243c7c',
    C: '#6b8fd8',
    c: '#243c7c',
    W: '#f3e6cc',
    P: '#9a8257',
    p: '#6e5a39',
    O: '#5a3a22',
    w: '#8b5a2b',
    o: { fill: '#e8641e', cls: 'sprite-orb' },
  },
};

// Small airship: striped balloon, wooden gondola, pennant. Original design.
export const airship = {
  rows: [
    '.........aaaaaaaaaa',
    '......aaAAAAAAAAAAaa',
    '....aaAAAAAAAAAAAAAAaa',
    '...aAAAAAAAAAAAAAAAAAAa',
    '..arrrrrrrrrrrrrrrrrrrra.f',
    '..aAAAAAAAAAAAAAAAAAAAAa.fF',
    '..arrrrrrrrrrrrrrrrrrrra.fFF',
    '...aAAAAAAAAAAAAAAAAAAa..f',
    '....aaAAAAAAAAAAAAAAaa...f',
    '......aaaaaaaaaaaaaa.....f',
    '.......l..l....l..l......f',
    '........l.l....l.l.......f',
    '....g....lHHHHHHl........f',
    '....gg.HHHHHHHHHHHHHH...ff',
    '.....pHHyHHyHHyHHyHHHHHHf',
    '......hhhhhhhhhhhhhhhhhh',
    '........hhhhhhhhhhhhhh',
  ],
  palette: {
    a: '#c9772e',
    A: '#e9806e',
    r: '#f3e6cc',
    l: '#3a2a1f',
    H: '#8b5a2b',
    h: '#5a3a22',
    y: { fill: '#fdb813', cls: 'sprite-lamps' },
    f: '#3a2a1f',
    F: '#e8641e',
    g: { fill: '#b9bcc8', cls: 'sprite-prop' },
    p: '#3a2a1f',
  },
};

// Campfire with two flame frames swapped by CSS.
export const campfire = {
  rows: [
    '.....1......',
    '....12.2....',
    '...1221.2...',
    '...12321....',
    '..1233321...',
    '..12333321..',
    '...123321...',
    '.LLL1221LLL.',
    'LLLLLLLLLLLL',
    '.ll.LLLL.ll.',
  ],
  palette: {
    1: { fill: '#e8641e', cls: 'sprite-flame' },
    2: { fill: '#fdb813', cls: 'sprite-flame' },
    3: { fill: '#fff4d6', cls: 'sprite-flame' },
    L: '#8b5a2b',
    l: '#5a3a22',
  },
};
